apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower-app-deployment
spec: #define the behaviour of the deployement
  replicas: 2
  selector:
    matchLabels:
      app: web
  template: #It defines the Pod Definitions
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: flower-contianer
        image: putturravi/sre-test-image:1.0
        resources:
          limits:
            memory: "500Mi"
            cpu: "300m"
          requests:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 3015
---
apiVersion: v1
kind: Service
metadata:
  name: flower-app-svc
spec:
  selector:
    app: web
  ports:
  - port: 3017 #Service port number on which you want to access the application
    targetPort: 3015 #on which port number your application is running
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flower-app-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flower-app-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target: 
        type: Utilization
        averageUtilization: 2
